# Generated by Django 5.1.4 on 2024-12-21 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('technology', models.CharField(choices=[('Python', 'Python'), ('Django', 'Django'), ('JavaScript', 'Javascript'), ('React', 'React'), ('Angular', 'Angular'), ('Flutter', 'Flutter'), ('HTML', 'Html'), ('CSS', 'Css'), ('Bootstrap', 'Bootstrap'), ('Materialize', 'Materialize'), ('MySQL', 'Mysql'), ('PostgreSQL', 'Postgresql'), ('MongoDB', 'Mongodb'), ('Firebase', 'Firebase'), ('Heroku', 'Heroku')], max_length=50)),
            ],
        ),
    ]
